owner: lu-brn
homepage_url: "http://www.bioinformatics.deib.polimi.it/genomic_computing/GMQL/"
categories: [Genomic Interval Operations]
repositories:
  gmql_auth:
    description: "Manage the registration, login and logout of users to the GMQL system."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - gmql_rest_auth.xml
      - gmql_rest_auth.py
  gmql_repository:
    description: "View, browse, rename or delete datasets in the user's space on the GMQL system."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_repository.xml
      - gmql_rest_datasets.py
  gmql_upload:
    description: "It allows uploading a new dataset on the user’s private space of the GMQL Repository."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_datasets_upload.xml
      - gmql_rest_datasets.py
  gmql_download:
    description: "It allows importing in the current Galaxy history the selected dataset from the GMQL Repository."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_datasets_download.xml
      - gmql_rest_datasets.py  
  gmql_queries_editor:
    description: "Compile and run GMQL queries (Advanced Mode)."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_queries_editor.xml
      - gmql_rest_queries.py
      - gmql_rest_datasets.py
  gmql_queries_monitor:
    description: "List the user's jobs and their status."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_queries_monitor.xml
      - gmql_rest_queries.py
      - gmql_rest_datasets.py
  gmql_queries_composer:
    description: "Create, Compile and Run GMQL queries step by step."
    include:
      - gmql_rest_macros.xml
      - utilities.py
      - gmql_rest.yaml
      - test-data
      - datatypes_conf.xml
      - gmql.py
      - dynamic_utils.py
      - gmql_rest_queries.py
      - gmql_rest_datasets.py
      - gmql_queries_composer.xml
      - gmql_queries_macros.xml
      - gmql_operators_select.xml
      - gmql_operators_order.xml
      - gmql_operators_join.xml
      - gmql_operators_map.xml
      - gmql_operators_project.xml
      - gmql_operators_cover.xml
      - gmql_operators_extend.xml
      - gmql_operators_group.xml
      - gmql_operators_merge_union_diff.xml
      - gmql_operators_tests.xml
      - gmql_queries_statements.py
      - gmql_queries_constants.py
      - gmql_syntax.yaml
suite:
  name: suite_gmql_galaxy
  description: Tool Suite to integratively use the GenoMetric Query Language within the Galaxy framework
  include_repositories:
  - name: gmql_auth
    owner: lu-brn
  - name: gmql_repository
    owner: lu-brn
  - name: gmql_upload
    owner: lu-brn
  - name: gmql_download
    owner: lu-brn
  - name: gmql_queries_editor
    owner: lu-brn
  - name: gmql_queries_monitor
    owner: lu-brn
  - name: gmql_queries_composer
    owner: lu-brn
owner: lu-brn

